### ISSUE TITLE
Raw analysis results beyond figure 1E 

### ISSUE THREAD

**Issue by bp6725** [Shamir-Lab/EMP-benchmark#1]
Hi
In the paper(DOMINO,2021) Fig.1E you compared the q-value distribution of the original GE to the permuted GE for the CBX data-set, do you have the same analysis for the other data-sets? I can't find the raw results beyond the figures. Thank you!

**Comment by hag007** [comment]
Hi bp6725,

I guess you meant Fig. 1A. This figure illustrates the bias of the enriched GO terms in different AMI algorithms.
You can generate raw results by using EMP for any given dataset: simply run EMP once (for a single permutation), calculate the enriched GO term, and compare it to the results of the original set 
 
Note that Fig. 2 E,F demonstrate the AMI bias more systematically (on distributions of 5000 permutations).
